### ISSUE TITLE
Error when running mnist example

### ISSUE THREAD

**Issue by lampts** [idiap/importance-sampling#5] opened 2017-08-25 06:49 UTC
I tried to run mnist example and got the following error. It seems to be related to Transparent_keras.
I've installed transparent-keras 0.2. How to fix that?

transparent_keras/transparent_model.pyc in _get_train_updates(self)
     77         updates += model.optimizer.get_updates(
     78             model._collected_trainable_weights,
---> 79             model.constraints,
     80             model.total_loss
     81         )

AttributeError: 'Model' object has no attribute 'constraints'

**Comment by angeloskath** [comment] 2017-08-25 09:58
It is a bug on Transparent Keras. Fixing it and releasing a patch.

Although it is a lame excuse on my part, the public attribute `constraints` disappeared from Keras version 2.0.6 to 2.0.7 and that is what is causing the bug.

I will close the issue when I have released the new version of transparent-keras. If you need a very quick fix, just install Keras 2.0.6 .

**Comment by angeloskath** [comment] 2017-08-25 10:27
I have released transparent-keras 0.3 and the problem is fixed. Sorry for the inconvenience. I will see if I can plan this better so that this never happens in the future.

There is a good chance that now you will need to install Keras 2.0.7 in order for everything to work. I am open to suggestions in order to avoid this problem in the future.

**Closed as completed by angeloskath** 2017-08-25 10:27 UTC
